spring.application.name=api

#1. Database Connection Settings (The Address)
spring.datasource.url= jdbc:postgresql://localhost:5443/vaultnote
spring.datasource.username=postgres
spring.datasource.password=mysecurepassword
spring.datasource.driver-class-name=org.postgresql.Driver

#2.Hibernate/JPA Settings (The Code-to-SQL Translator)
spring.jpa.properties.spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect

#"update" tells Spring Boot to automatically inspect our User.java class and
#create the "users" table inside PostgreSQL if it doesnt exist yet!
spring.jpa.hibernate.ddl-auto=update

#prints all the sql statements in the terminal so we can see whats happening
spring.jpa.show-sql=true

#3.Server port
server.port=8080